### ISSUE TITLE
Console output says port is busy but in reality it isnt

### ISSUE THREAD

**Issue by baarse** [jenkinsci/selenium-plugin#131] opened 2018-08-09 08:08 UTC
I have jenkins running in a docker container and when trying to connect to the selenium grid hub the console output looks like this:

`Starting Selenium Grid
[jenkins_home] $ /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp /var/jenkins_home/war/WEB-INF/lib/remoting-3.21.jar hudson.remoting.Launcher -cp /var/jenkins_home/plugins/selenium/WEB-INF/lib/selenium-server-standalone-3.12.0.jar:/var/jenkins_home/plugins/selenium/WEB-INF/lib/htmlunit-driver-standalone-2.29.2.jar -connectTo localhost:39799
Starting Selenium Grid
channel started
Aug 09, 2018 5:54:46 AM hudson.plugins.selenium.HubLauncher call
OFF: Grid hub starting with log level INFO
Aug 09, 2018 5:54:46 AM hudson.plugins.selenium.HubLauncher call
OFF: Grid Hub preparing to start on port 4455
2018-08-09 05:54:49.725:INFO::pool-1-thread-2 for channel id=0: Logging initialized @19728ms to org.seleniumhq.jetty9.util.log.StdErrLog
2018-08-09 05:54:50.028:INFO:osjs.Server:pool-1-thread-2 for channel id=0: jetty-9.4.7.v20170914, build timestamp: 2017-11-21T21:27:37Z, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2018-08-09 05:54:50.166:INFO:osjs.session:pool-1-thread-2 for channel id=0: DefaultSessionIdManager workerName=node0
2018-08-09 05:54:50.174:INFO:osjs.session:pool-1-thread-2 for channel id=0: No SessionScavenger set, using defaults
2018-08-09 05:54:50.185:INFO:osjs.session:pool-1-thread-2 for channel id=0: Scavenging every 600000ms
2018-08-09 05:54:50.200:INFO:osjsh.ContextHandler:pool-1-thread-2 for channel id=0: Started o.s.j.s.ServletContextHandler@1b5ef1eb{/,null,AVAILABLE}
Aug 09, 2018 5:54:50 AM org.openqa.grid.internal.DefaultGridRegistry assignRequestToProxy
INFO: Shutting down registry.
2018-08-09 05:54:50.251:INFO:osjs.AbstractConnector:pool-1-thread-2 for channel id=0: Stopped ServerConnector@614a4fe3{HTTP/1.1,[http/1.1]}{192.168.99.100:4455}
2018-08-09 05:54:50.266:INFO:osjs.session:pool-1-thread-2 for channel id=0: Stopped scavenging
2018-08-09 05:54:50.288:INFO:osjsh.ContextHandler:pool-1-thread-2 for channel id=0: Stopped o.s.j.s.ServletContextHandler@1b5ef1eb{/,null,UNAVAILABLE}
Aug 09, 2018 5:54:50 AM org.openqa.grid.web.Hub start
SEVERE: Port 4455 is busy, please choose a free port for the hub and specify it using -port option
Aug 09, 2018 5:54:50 AM hudson.plugins.selenium.HubLauncher call
OFF: Grid Hub started on port 4455 with args: -maxSession 5 -timeout 300 -browserTimeout 0 -host 192.168.99.100
Aug 09, 2018 7:57:59 AM org.jenkinsci.remoting.util.AnonymousClassWarnings warn
WARNING: Attempt to (de-)serialize anonymous class hudson.plugins.selenium.PluginImpl$1; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
`

The port 4455 isnt used for anything else other than the selenium hub.

**Comment by alinpa** [comment] 2018-08-16 13:26
@baarse Take a look to this: https://github.com/jenkinsci/selenium-plugin/issues/128

**Comment by baarse** [comment] 2018-08-20 05:50
@alinpa thank you!

**Comment by Mobrockers** [comment] 2018-08-31 19:40
Since it's confirmed this is not a problem with the plugin I'll close this issue.

**Closed by Mobrockers** 2018-08-31 19:40 UTC
Labels: Not A Bug
