### ISSUE TITLE
The selenium hub it doesn't start

### ISSUE THREAD

**Issue by alinpa** [jenkinsci/selenium-plugin#128] opened 2018-06-07 16:06 UTC
Steps to reproduce:
 - I updated the plugin from 3.9 to the latest version 3.12.0.
- Restart your jenkins
- Check the selenium plugin console log: 
** Starting Selenium Grid
[jenkins_home] $ /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp /var/jenkins_home/war/WEB-INF/lib/remoting-3.17.jar hudson.remoting.Launcher -cp /var/jenkins_home/plugins/selenium/WEB-INF/lib/selenium-server-standalone-3.12.0.jar:/var/jenkins_home/plugins/selenium/WEB-INF/lib/selenium-server-standalone-3.12.0.jar -connectTo localhost:41409
Starting Selenium Grid
channel started
Jun 07, 2018 3:49:21 PM hudson.plugins.selenium.HubLauncher call
OFF: Grid hub starting with log level ALL
Jun 07, 2018 3:49:21 PM hudson.plugins.selenium.HubLauncher call
OFF: Grid Hub preparing to start on port 4444
2018-06-07 15:49:22.528:INFO::pool-1-thread-1 for channel id=49: Logging initialized @2529ms to org.seleniumhq.jetty9.util.log.StdErrLog
2018-06-07 15:49:22.622:INFO:osjs.Server:pool-1-thread-1 for channel id=49: jetty-9.4.7.v20170914, build timestamp: 2017-11-21T21:27:37Z, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2018-06-07 15:49:22.657:INFO:osjs.session:pool-1-thread-1 for channel id=49: DefaultSessionIdManager workerName=node0
2018-06-07 15:49:22.657:INFO:osjs.session:pool-1-thread-1 for channel id=49: No SessionScavenger set, using defaults
2018-06-07 15:49:22.659:INFO:osjs.session:pool-1-thread-1 for channel id=49: Scavenging every 660000ms
2018-06-07 15:49:22.668:INFO:osjsh.ContextHandler:pool-1-thread-1 for channel id=49: Started o.s.j.s.ServletContextHandler@3b6e23d0{/,null,AVAILABLE}
Jun 07, 2018 3:49:22 PM org.openqa.grid.internal.DefaultGridRegistry assignRequestToProxy
INFO: Shutting down registry.
2018-06-07 15:49:22.677:INFO:osjs.AbstractConnector:pool-1-thread-1 for channel id=49: Stopped ServerConnector@551461d7{HTTP/1.1,[http/1.1]}{xxx.xxx.xxx.xxx:4444}
2018-06-07 15:49:22.678:INFO:osjs.session:pool-1-thread-1 for channel id=49: Stopped scavenging
2018-06-07 15:49:22.680:INFO:osjsh.ContextHandler:pool-1-thread-1 for channel id=49: Stopped o.s.j.s.ServletContextHandler@3b6e23d0{/,null,UNAVAILABLE}
Jun 07, 2018 3:49:22 PM org.openqa.grid.web.Hub start
SEVERE: Port 4444 is busy, please choose a free port for the hub and specify it using -port option
Jun 07, 2018 3:49:22 PM hudson.plugins.selenium.HubLauncher call
OFF: Grid Hub started on port 4444 with args: -maxSession 5 -timeout 30 -browserTimeout 0 -host xxx.xxx.xxx.xxx
channel stopped**

- If I execute the following command "ps -aux | grep -ie "selenium" " on the jenkins machine  the output is: 

root       130  0.6  0.5 6780788 87364 ?       Sl   15:32   0:13 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp /var/jenkins_home/war/WEB-INF/lib/remoting-3.17.jar hudson.remoting.Launcher -cp /var/jenkins_home/selenium-server-standalone-3.12.0.jar:/var/jenkins_home/selenium-server-standalone-3.12.0.jar -connectTo localhost:40799

root       228  1.3  0.9 7457004 154404 ?      Sl   15:49   0:11 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp /var/jenkins_home/war/WEB-INF/lib/remoting-3.17.jar hudson.remoting.Launcher -cp /var/jenkins_home/plugins/selenium/WEB-INF/lib/selenium-server-standalone-3.12.0.jar:/var/jenkins_home/plugins/selenium/WEB-INF/lib/selenium-server-standalone-3.12.0.jar -connectTo localhost:41409
  **Why I have these two processes? Should be only one?

- on the node I can see the following error message:
[SelfRegisteringRemote$1.run] - Couldn't register this node: The hub is down or not responding: Failed to connect to /xxx.xxx.xxx.xxx

**- I have checked if the port is already in use, but is not. 

Any idea why is happening this?

**Comment by alinpa** [comment] 2018-06-07 16:10
Hello @dmitryyu  and @ryantrevisol

Do you have any idea why I have this issue on this version?

**Comment by alinpa** [comment] 2018-06-08 11:10
Hi @dmitryyu, 

I have tried what you have suggested me without success.

I removed the plugin, I installed again and the only one is that I can see only one process(it is an improvement :) )
But I still have the issue regarding 4444 port is busy.
**Now I can see the following process started :

root     19985  0.7  1.1 7752140 189304 ?      Sl   09:41   0:38 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp /var/jenkins_home/war/WEB-INF/lib/remoting-3.20.jar hudson.remoting.Launcher -cp /var/jenkins_home/plugins/selenium/WEB-INF/lib/selenium-server-standalone-3.12.0.jar:/var/jenkins_home/plugins/selenium/WEB-INF/lib/selenium-server-standalone-3.12.0.jar -connectTo localhost:40311

Do you have any other idea?

**Comment by dmitryyu** [comment] 2018-06-08 11:20
Process of port verification wasn't changed.
So i believe it's not related to the plugin. 
Something on your end uses the port.  
Some possible cases:
1. Hub and node use the same port. (to check it turn off jenkins/selenium nodes) and start/restart selenium hub.
2. Something else uses the port -  (check what's the process uses the port ) 

i don't have other ideas - i guess if system writes that port is busy - it's so.

**Comment by alinpa** [comment] 2018-06-08 11:38
The jenins is running in a container.

**Comment by alinpa** [comment] 2018-06-08 12:10
@dmitryyu : Can you copy-paste the command from selenium.log (how is started the selenium-grid)?

**Comment by dmitryyu** [comment] 2018-06-08 12:55
Starting Selenium Grid
[JenkinsInstallDir] $ D:\JenkinsInstallDir\jre\bin\java -cp D:\JenkinsInstallDir\war\WEB-INF\lib\remoting-3.16.jar hudson.remoting.Launcher -cp D:\JenkinsInstallDir\plugins\selenium\WEB-INF\lib\selenium-server-standalone-3.12.0.jar;D:\JenkinsInstallDir\plugins\selenium\WEB-INF\lib\htmlunit-driver-standalone-2.29.2.jar -connectTo localhost:55442
Starting Selenium Grid
channel started
Jun 07, 2018 7:29:27 PM hudson.plugins.selenium.HubLauncher call
OFF: Grid hub starting with log level WARNING
Jun 07, 2018 7:29:27 PM hudson.plugins.selenium.HubLauncher call
OFF: Grid Hub preparing to start on port 4444
2018-06-07 19:29:33.140:INFO::pool-1-thread-1 for channel id=0: Logging initialized @54713ms to org.seleniumhq.jetty9.util.log.StdErrLog
2018-06-07 19:29:33.568:INFO:osjs.Server:pool-1-thread-1 for channel id=0: jetty-9.4.7.v20170914, build timestamp: 2017-11-22T00:27:37+03:00, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2018-06-07 19:29:33.718:INFO:osjs.session:pool-1-thread-1 for channel id=0: DefaultSessionIdManager workerName=node0
2018-06-07 19:29:33.718:INFO:osjs.session:pool-1-thread-1 for channel id=0: No SessionScavenger set, using defaults
2018-06-07 19:29:33.718:INFO:osjs.session:pool-1-thread-1 for channel id=0: Scavenging every 660000ms
2018-06-07 19:29:33.750:INFO:osjsh.ContextHandler:pool-1-thread-1 for channel id=0: Started o.s.j.s.ServletContextHandler@1f5419c{/,null,AVAILABLE}
2018-06-07 19:29:33.843:INFO:osjs.AbstractConnector:pool-1-thread-1 for channel id=0: Started ServerConnector@aeef06{HTTP/1.1,[http/1.1]}{COMP_NAME:4444}
2018-06-07 19:29:33.843:INFO:osjs.Server:pool-1-thread-1 for channel id=0: Started @55421ms
Jun 07, 2018 7:29:33 PM org.openqa.grid.web.Hub start
INFO: Selenium Grid hub is up and running
Jun 07, 2018 7:29:33 PM org.openqa.grid.web.Hub start

**Comment by alinpa** [comment] 2018-06-08 13:23
Hi @dmitryyu, 

I think I found the issue and I will try to describe the setup:
I have an ec2 machine and on this I start my jenkins image.(the network container used bidge network)
On jenkins ->  Manage Jenkins -> Configure System -> Selenium(press Advanced port), under Hostname resolver you can find two radiobuttons: 1)Use a fixed hostname 2) Use jenkins URL, as defined in the global configuration
This parameter is documented wrong  like as : This will use the specified hostname to tell the node where to connect to the hub.
But is wrong because is used for different purposes.
They said  this bind the address specificated inside of this field, and  if you put host ip, this one cannot be resolved inside of the container and the error returned is incorrect. take a look to this class 
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/web/Hub.java line 249. BindException is not only for the port(if is not available, it can be thrown when the address is not available).

if (e instanceof BindException) {
        log.severe(String.format(
            "Port %s is busy, please choose a free port for the hub and specify it using -port option", config.port));

The java doc says: Signals that an error occurred while attempting to bind a socket to a local address and port. Typically, the port is in use, or the requested local address could not be assigned.(https://docs.oracle.com/javase/7/docs/api/java/net/BindException.html)

**Comment by alinpa** [comment] 2018-06-08 13:27
@dmitryyu if i fill the "Use a fixed hostname" with 0.0.0.0 and restrat the plugin, it is working.

**Comment by Mobrockers** [comment] 2018-06-11 07:53
Feel free to provide a fix for the issue as you see it

**Comment by alinpa** [comment] 2018-06-11 07:57
I want but I don't know very well the code.

**Comment by alinpa** [comment] 2018-06-11 08:11
I think this  is the possible issue: 
https://github.com/SeleniumHQ/selenium/commit/6404eef633b5275204feaa0307ffda9cd20cd62e

**Comment by hooligan495** [comment] 2018-06-12 19:15
This one bit me as well.  Thanks for the work around above it solves my problem for now I will keep an eye on this issue for the fix.

**Comment by Mobrockers** [comment] 2018-08-31 19:40
Since it's confirmed this is not a problem with the plugin I'll close this issue.

**Closed by Mobrockers** 2018-08-31 19:40 UTC
Labels: Not A Bug
