### ISSUE TITLE
Restarting Slave/Configuration causing IEDriverServer to be overwritten

### ISSUE THREAD

**Issue by zdmeyers** [jenkinsci/selenium-plugin#94] opened 2016-06-20 14:56 UTC
If I already have a version of IEDriverServer on the slave machine, then restarting the node or configuration shouldn't overwrite the current one. I keep replacing the 64-bit IEDriverServer.exe with the 32-bit version, but when I restart the node or configuration, it gets replaced by the 64-bit version. I do not want to use the 64-bit version due to the slow typing issue.

**Comment by Mobrockers** [comment] 2016-06-20 14:58
Duplicate of #72

**Comment by Mobrockers** [comment] 2017-12-22 12:16
You can now choose your IEDriver version.

**Closed by Mobrockers** 2017-12-22 12:16 UTC
