### ISSUE TITLE
Plugin delivering empty JAR file to node

### ISSUE THREAD

**Issue by jameswtelfer** [jenkinsci/selenium-plugin#118] opened 2018-01-18 12:12 UTC
Having updated to version 3.7.1 (from 3.1.0), my single Selenium node no longer starts the configuration.  The Node is online according to Jenkins, and manually attempting to start the Selenium node simply refreshes the node management page.

Looking at the node itself, when this happens the new selenium-server-standalone-3.7.1.jar file is created, but is empty.  Replacing this with the version from the repo has no effect, as it gets overwritten by the empty file again.  The file on the Jenkins master is correct, at least in size.

Anyone any other ideas of what to try?

**Comment by dmitryyu** [comment] 2018-02-06 10:43
could you please make sure that 
1. you have full access to the folder on the node). Please check it under the user who starts Jenkins node. 
2. The node has enough free space for a possibility to upload the file.
and provide details of your OS, logs.

**Comment by jameswtelfer** [comment] 2018-02-09 16:02
1. The folder on the node is owned by the jenkins user, and they have full control.
2. There are 10s of GBs free space
3. Node is running WIndows 10, jenkins master is running on Ubuntu 16.04.

There isn't anything different in the logs from the point where this occurred vs. when it was working under version 3.1.0.

**Comment by dmitryyu** [comment] 2018-02-13 22:15
It's a bit strange, nothing was changed in this area.
But i have an idea, and answers on the following questions will allow me to confirm/decline it:
1. Does the node use HtmlUnit browser/instances ? if so, try to exclude htmlunit instances and check it again.

Also some other questions:
1. Is it always reproduced? 
2. is it reproduced for other nodes? for node with another OS ? from the same master node.
3. Could you please provide a log from Jenkins node (find your node on the page https://your_jenkins_host:port/computer/ )
4. also it would be useful to get jenkins logs in any case.

**Comment by jameswtelfer** [comment] 2018-02-20 18:44
I finally got around to throwing together a sandbox environment to check this, and felt very stupid afterwards. I’d completely missed the logs on the master telling me the slave wasn’t allowed to access the jar file on the master, because the master-slave security was enabled. Turns out the production instance had a very specific rule to allow access to the old file.

**Comment by Mobrockers** [comment] 2018-03-05 07:11
I assume the problem is fixed now and will close this issue. Thanks @dmitryyu for helping out @jameswtelfer

**Closed by Mobrockers** 2018-03-05 07:11 UTC
